name: Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_NATOURS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install git if not present
            if ! command -v git &> /dev/null; then
              sudo yum install -y git
            fi

            # Install Node.js if not present
            if ! command -v node &> /dev/null; then
              curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Install PM2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Install and configure nginx if not present
            if ! command -v nginx &> /dev/null; then
              sudo yum install -y nginx
              sudo systemctl enable nginx
            fi

            # Configure nginx for Node.js reverse proxy
            if [ ! -f /etc/nginx/conf.d/natours.conf ]; then
              sudo tee /etc/nginx/conf.d/natours.conf > /dev/null <<'EOF'
            server {
                listen 80;
                server_name _;

                location / {
                    proxy_pass http://127.0.0.1:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            EOF
              sudo systemctl restart nginx
            fi

            # Create directory and clone repo if not present
            if [ ! -d /var/www/natours ]; then
              sudo mkdir -p /var/www
              cd /var/www
              sudo git clone https://github.com/N73311/natours.git
              sudo chown -R ec2-user:ec2-user /var/www/natours
            fi

            cd /var/www/natours
            git pull origin master
            npm ci
            npm run build:js
            pm2 restart natours || pm2 start server.js --name natours
            pm2 save
            sudo pm2 startup systemd -u ec2-user --hp /home/ec2-user